// Copyright (c) 2021-Present XiHanFun and contributors.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Text;
using XiHan.BasicApp.CodeGeneration.Domain.Generation;
using Shared = XiHan.BasicApp.CodeGeneration.Infrastructure.Generation.MenuPermissionArtifactShared;

namespace XiHan.BasicApp.CodeGeneration.Infrastructure.Generation;

/// <summary>
/// 菜单/权限二阶产物生成器（权限码常量类 + 落地 README）
/// </summary>
/// <remarks>
/// 形态：生成"待并入源码"的代码片段 → 重建库经既有 Seeder 链生效，符合 XiHan 单一事实源约定，
/// 不做运行时写库（避免与重建库覆盖冲突）。权限码沿用 {资源}:{操作} 两段式，资源段取表名（snake）。
/// 权限码集合随表配置 EnabledActions 裁剪：只生成实际会产出接口/按钮的动作（读取基线 read 恒在）。
/// </remarks>
public static class MenuPermissionArtifactGenerator
{
    /// <summary>
    /// 构建权限码常量 + 落地 README
    /// </summary>
    /// <param name="context">生成上下文</param>
    /// <param name="collidingCodes">已存在于系统的权限码（生成前查库得到，用于 README 顶部醒目告警；为空表示无冲突）</param>
    public static IReadOnlyList<GeneratedArtifact> Build(CodeGenerationContext context, IReadOnlyCollection<string> collidingCodes)
    {
        ArgumentNullException.ThrowIfNull(context);
        ArgumentNullException.ThrowIfNull(collidingCodes);

        return
        [
            BuildPermissionCodes(context),
            BuildReadme(context, collidingCodes)
        ];
    }

    /// <summary>
    /// 权限码常量类（drop-in：放入 {模块}/Domain/Permissions/）
    /// </summary>
    private static GeneratedArtifact BuildPermissionCodes(CodeGenerationContext context)
    {
        var resource = Shared.Resource(context);
        var ns = Shared.ResolveNamespace(context);
        var className = $"{context.ClassName}PermissionCodes";

        var sb = new StringBuilder();
        Shared.AppendCSharpFileHeader(sb);
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}.Domain.Permissions;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// {context.ClassName} 权限码常量（资源 {resource} × 已启用操作）");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>资源编码</summary>");
        sb.AppendLine($"    public const string Resource = \"{resource}\";");
        foreach (var action in Shared.EffectiveActions(context))
        {
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>{Shared.MetaOf(action).Title}权限</summary>");
            sb.AppendLine($"    public const string {Shared.Pascalize(action)} = \"{resource}:{action}\";");
        }

        sb.AppendLine("}");

        var fileName = $"{className}.cs";
        return new GeneratedArtifact($"{Shared.PermissionsFolder}/{fileName}", fileName, sb.ToString(), Shared.TemplateCode, Side: ArtifactSide.Backend);
    }

    /// <summary>
    /// 落地 README（产物清单 + 3 步落地；权限码冲突时顶部醒目告警）
    /// </summary>
    private static GeneratedArtifact BuildReadme(CodeGenerationContext context, IReadOnlyCollection<string> collidingCodes)
    {
        var resource = Shared.Resource(context);
        var ns = Shared.ResolveNamespace(context);
        var display = Shared.Display(context);
        var kebab = Shared.Kebab(context);
        var actions = Shared.EffectiveActions(context);

        var sb = new StringBuilder();
        sb.AppendLine($"# {display} 菜单与权限 · 落地说明");
        sb.AppendLine();

        if (collidingCodes.Count > 0)
        {
            sb.AppendLine("> ⚠️ **权限码冲突**：以下权限码在系统中已存在，直接并入会与既有资源撞码。");
            sb.AppendLine("> 请先确认表名（资源段）是否与既有模块重名，必要时调整表名或资源段后重新生成：");
            sb.AppendLine(">");
            foreach (var code in collidingCodes)
            {
                sb.AppendLine($"> - `{code}`");
            }

            sb.AppendLine();
        }

        sb.AppendLine("> 接线产物是「待并入源码」的代码，不是运行时写库。路径都相对后端模块项目根：生成到项目时已直接落位，下载压缩包时按同样的相对位置放进模块。");
        sb.AppendLine("> 权限与菜单以登记类声明，由平台的汇总种子在启动播种时写入平台库（符合 XiHan 单一事实源约定），不是运行时写库。");
        sb.AppendLine();
        sb.AppendLine("## 1. 权限码");
        sb.AppendLine();
        sb.AppendLine($"资源 `{resource}` × 已启用操作，两段式 `{{资源}}:{{操作}}`（同 `code_gen:read`）：");
        sb.AppendLine();
        sb.AppendLine("| 权限码 | 说明 | 需审计 |");
        sb.AppendLine("| --- | --- | --- |");
        foreach (var action in actions)
        {
            var meta = Shared.MetaOf(action);
            sb.AppendLine($"| `{resource}:{action}` | {meta.Title} | {(meta.IsRequireAudit ? "是" : "否")} |");
        }

        sb.AppendLine();
        sb.AppendLine("## 2. 产物清单");
        sb.AppendLine();
        sb.AppendLine($"| 文件 | 位置（`{ns}` 项目内） | 写入策略 |");
        sb.AppendLine("| --- | --- | --- |");
        sb.AppendLine($"| `{context.ClassName}PermissionCodes.cs` | `{Shared.PermissionsFolder}/` | 总是覆盖（纯推导） |");
        sb.AppendLine($"| `{context.ClassName}PermissionDefinitions.cs` | `{Shared.PermissionsFolder}/` | 总是覆盖（纯推导） |");
        sb.AppendLine($"| `{context.ClassName}PermissionCatalog.cs` | `{Shared.SeedersFolder}/`（权限目录登记：资源与权限） | 总是覆盖（随包含操作推导） |");
        sb.AppendLine($"| `{context.ClassName}MenuPages.cs` | `{Shared.SeedersFolder}/`（菜单登记：页面与按钮） | 总是覆盖（随包含操作、父菜单推导） |");
        sb.AppendLine($"| `{context.ClassName}PageRegistry.snippet.txt` | `{Shared.OutputFolder}/`（并进模块自己的 `PageRegistry` 时粘贴，与 MenuPages 二选一） | 参考片段 |");
        sb.AppendLine();
        sb.AppendLine("## 3. 落地步骤（4 步）");
        sb.AppendLine();
        sb.AppendLine("1. **确认文件**：权限码常量类、权限定义类与两个登记类按上表落在模块里（生成到项目时已写好，下载压缩包时照表放置）。");
        sb.AppendLine("   生成的 AppService/QueryService 已逐方法标注 `[PermissionAuthorize(" + context.ClassName + "PermissionCodes.Xxx)]`，");
        sb.AppendLine("   引用的就是 `" + Shared.PermissionsFolder + "/` 下的权限码常量类——缺了它后端编译不过。");
        sb.AppendLine("2. **不用登记种子**：两个登记类按约定注册，由平台的汇总种子在权限目录、菜单两个阶段最后统一写入，");
        sb.AppendLine("   不需要 `AddDataSeeder<>`，也没有自己的种子顺序号。旧版本生成的 `" + context.ClassName + "PermissionSeeder` / `" + context.ClassName + "MenuSeeder` 及其登记要删掉，否则会重复写入。");
        var buttons = Shared.EnabledButtons(context).ToList();
        sb.AppendLine("3. **页面与按钮**：`" + context.ClassName + "MenuPages` 已登记页面行与已启用操作的按钮行，" + (context.ParentMenuCode is null ? "页面是顶级菜单（表配置里选「父菜单」可挂到平台目录下）。" : "页面挂在目录 `" + context.ParentMenuCode + "` 下。"));
        if (buttons.Count > 0)
        {
            sb.AppendLine("   生成页面的" + string.Join("/", buttons.Select(button => button.Title)) + "按钮用按钮码 `" + Shared.PageCode(context) + ".{"
                + string.Join("|", buttons.Select(button => button.Key)) + "}` 门控，按钮码只由菜单的按钮行下发。");
        }

        if (actions.Contains(CodeGenActions.Export))
        {
            sb.AppendLine("   导出中心接单的 `" + context.ClassName + "ExportProvider` 随后端产物生成，带 `IScopedDependency` 由框架约定注册，不必登记。");
        }

        if (context.EnabledActions.Contains(CodeGenActions.Print))
        {
            sb.AppendLine("   打印按钮跟查看权限走，另需打印模板的使用权限 `print-template:use`。打印数据源 `" + context.ClassName + "PrintDataSource` 随后端产物生成，");
            sb.AppendLine("   须在模块 `ConfigureServices` 里 `services.RegisterPrintDataSource(" + context.ClassName + "PrintDataSource.Definition)` 登记（模块须依赖打印模块），");
            sb.AppendLine("   再到「打印模板」页新建编码为 `" + Shared.PageCode(context) + "` 的模板、数据源选它。");
        }

        sb.AppendLine("   若要并进模块自己的 `PageRegistry`，把 `" + context.ClassName + "PageRegistry.snippet.txt` 的条目粘进去并删掉 `" + context.ClassName + "MenuPages`，不要两边都登记。");
        sb.AppendLine("4. **重启后端**：启动播种（开发环境默认开启）按权限码、菜单码对齐，权限、菜单、按钮即到位，不需要重建数据库。");
        sb.AppendLine("   排序、启停、显隐在菜单管理页调整，重启不会冲掉。超管在平台天然拥有全部权限；租户要用，由运营把权限授给套餐与角色。");
        sb.AppendLine();
        sb.AppendLine("> 菜单规格：MenuCode=`" + Shared.PageCode(context) + "`、Path=`/" + Shared.ModuleLower(context) + "/" + kebab + "`、Component=`" + Shared.Component(context) + "`、RouteName=`" + Shared.RouteName(context) + "`、I18nKey 留空（菜单名直接显示业务名称；要多语言时改成 `menu." + Shared.ModuleLower(context) + "_" + kebab.Replace('-', '_') + "` 并在前端各语言 menu.ts 补键）、绑定 `" + resource + ":read` 可见性。");
        sb.AppendLine($"> 父菜单：{(context.ParentMenuCode is null ? "未选 → 顶级菜单（在表配置里选「父菜单」可挂到平台目录下）" : $"`{context.ParentMenuCode}`（表配置所选目录的菜单码）")}。");
        sb.AppendLine();
        sb.AppendLine("> **勿改 `.Generated.cs`**：生成产物分自动文件（`.Generated.cs`/`.generated.ts`，总是覆盖）与手动文件（首次创建、永不覆盖）。自定义代码写在手动文件里。");

        return new GeneratedArtifact($"{Shared.OutputFolder}/README.md", "README.md", sb.ToString(), Shared.TemplateCode, Side: ArtifactSide.Backend);
    }
}
