// Copyright (c) 2021-Present XiHanFun and contributors.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Text;
using XiHan.BasicApp.CodeGeneration.Domain.Enums;
using XiHan.BasicApp.CodeGeneration.Domain.Generation;
using Shared = XiHan.BasicApp.CodeGeneration.Infrastructure.Generation.MenuPermissionArtifactShared;

namespace XiHan.BasicApp.CodeGeneration.Infrastructure.Generation;

/// <summary>
/// 种子登记二阶产物生成器（{Class}PermissionCatalog.cs + {Class}MenuPages.cs）
/// </summary>
/// <remarks>
/// 产出的不是种子，而是交给平台汇总种子的登记：权限目录实现 IPermissionCatalogContribution（资源 + 资源 × 操作的权限），
/// 菜单实现 IMenuPageContribution（页面行 + 按钮行）。两者按约定注册（ExposeServices + ITransientDependency），
/// 由 SaaS 的汇总种子在权限目录、菜单两个阶段最后统一写入：业务模块不需要登记种子，也不各自占种子顺序号。
/// 内容全部由表配置推导（包含操作、父菜单），标 <see cref="ArtifactWriteMode.AlwaysOverwrite"/>，重新生成即随配置更新。
/// 权限项来源为同批生成的 {Class}PermissionDefinitions，按钮的权限码来自同批生成的 {Class}PermissionCodes，避免两处描述。
/// </remarks>
internal static class SeederArtifactGenerator
{
    /// <summary>
    /// 构建权限目录登记与菜单登记
    /// </summary>
    public static IReadOnlyList<GeneratedArtifact> Build(CodeGenerationContext context)
    {
        ArgumentNullException.ThrowIfNull(context);

        return
        [
            Artifact(context, "PermissionCatalog", PermissionCatalogTemplate),
            Artifact(context, "MenuPages", MenuPagesTemplate)
        ];
    }

    private static GeneratedArtifact Artifact(CodeGenerationContext context, string suffix, string template)
    {
        var fileName = $"{context.ClassName}{suffix}.cs";
        return new GeneratedArtifact($"{Shared.SeedersFolder}/{fileName}", fileName, Fill(template, context), Shared.TemplateCode, ArtifactWriteMode.AlwaysOverwrite, ArtifactSide.Backend);
    }

    /// <summary>
    /// 占位替换（原始字符串模板含大量 C# 花括号/内插，用 %TOKEN% 占位避免转义）
    /// </summary>
    /// <remarks>
    /// 显示名是业务名称的自由文本：进字符串字面量的 %DISPLAY% 按 C# 字符串转义，
    /// 进文档注释的 %DISPLAY_DOC% 按 XML 转义，否则引号、反斜杠、尖括号都会让登记编译不过。
    /// </remarks>
    private static string Fill(string template, CodeGenerationContext context)
    {
        var display = Shared.Display(context);
        return template
            .Replace("%NS%", Shared.ResolveNamespace(context))
            .Replace("%CLASS%", context.ClassName)
            .Replace("%MODULE%", Shared.ModuleSegment(context))
            .Replace("%DISPLAY_DOC%", TemplateTextEscaper.XmlDoc(display))
            .Replace("%DISPLAY%", TemplateTextEscaper.CSharpString(display))
            .Replace("%RESOURCE%", Shared.Resource(context))
            .Replace("%PAGECODE%", Shared.PageCode(context))
            .Replace("%PATH%", $"/{Shared.ModuleLower(context)}/{Shared.Kebab(context)}")
            .Replace("%COMPONENT%", Shared.Component(context))
            .Replace("%ROUTE%", Shared.RouteName(context))
            .Replace("%PARENT%", context.ParentMenuCode is null ? "null" : $"\"{TemplateTextEscaper.CSharpString(context.ParentMenuCode)}\"")
            .Replace("%BUTTONS%", BuildButtons(context));
    }

    /// <summary>
    /// 按钮行（已启用的写操作与打印）；查询与详情走列表页的读取权限，没有独立按钮
    /// </summary>
    private static string BuildButtons(CodeGenerationContext context)
    {
        var pageCode = Shared.PageCode(context);
        var sb = new StringBuilder();
        var sort = 1;
        foreach (var button in Shared.EnabledButtons(context))
        {
            sb.AppendLine($"        new(\"{pageCode}.{button.Key}\", \"{button.Title}\", \"{pageCode}\", {context.ClassName}PermissionCodes.{Shared.Pascalize(button.Action)}, {sort}),");
            sort++;
        }

        return sb.ToString().TrimEnd();
    }

    private const string PermissionCatalogTemplate = """
// Copyright (c) 2021-Present XiHanFun and contributors.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />
// 本文件由代码生成器产出，重新生成时整体覆盖：权限随表配置的包含操作推导，请勿手工编辑。

using %NS%.Domain.Permissions;
using XiHan.BasicApp.Saas.Domain.Entities;
using XiHan.BasicApp.Saas.Infrastructure.Seeders;
using XiHan.Framework.Core.DependencyInjection;
using XiHan.Framework.Core.DependencyInjection.ServiceLifetimes;

namespace %NS%.Infrastructure.Seeders;

/// <summary>
/// %DISPLAY_DOC% 权限目录登记：资源与「资源 × 已启用操作」的权限
/// </summary>
/// <remarks>
/// 按约定注册，由平台的汇总种子在权限目录阶段最后统一写入平台库：不需要在模块里登记种子，也没有自己的种子顺序号。
/// 操作来自平台操作字典（OperationSeeds）；作用侧两侧生效。
/// 权限只需声明，超管在平台天然拥有全部权限，租户的角色与套餐白名单由运营授予。
/// </remarks>
[ExposeServices(typeof(IPermissionCatalogContribution))]
public sealed class %CLASS%PermissionCatalog : IPermissionCatalogContribution, ITransientDependency
{
    private static readonly ResourceSeed Resource = new(
        %CLASS%PermissionDefinitions.Resource,
        %CLASS%PermissionDefinitions.ResourceName,
        %CLASS%PermissionDefinitions.ResourcePath,
        %CLASS%PermissionDefinitions.ResourceName + "接口",
        0);

    /// <summary>登记名</summary>
    public string Name => "[%MODULE%]%DISPLAY%权限目录";

    /// <summary>模块编码</summary>
    public string ModuleCode => %CLASS%PermissionDefinitions.Module;

    /// <summary>资源</summary>
    public IReadOnlyList<ResourceSeed> Resources { get; } = [Resource];

    /// <summary>权限（资源 × 已启用操作）</summary>
    public IReadOnlyList<PermissionSeed> Permissions { get; } =
    [
        .. %CLASS%PermissionDefinitions.Items.Select((item, index) => new PermissionSeed(
            $"{Resource.Code}:{item.Action}",
            item.Name,
            item.Description,
            Resource.Code,
            PermissionSide.Both,
            item.IsRequireAudit,
            9000 + index,
            Resource,
            OperationSeeds.All.Single(operation => operation.Code == item.Action)))
    ];
}
""";

    private const string MenuPagesTemplate = """
// Copyright (c) 2021-Present XiHanFun and contributors.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// <auto-generated />
// 本文件由代码生成器产出，重新生成时整体覆盖：页面与按钮随表配置（包含操作、父菜单）推导，请勿手工编辑。

using %NS%.Domain.Permissions;
using XiHan.BasicApp.Saas.Application.Pages;
using XiHan.BasicApp.Saas.Domain.Entities;
using XiHan.BasicApp.Saas.Infrastructure.Seeders;
using XiHan.Framework.Core.DependencyInjection;
using XiHan.Framework.Core.DependencyInjection.ServiceLifetimes;

namespace %NS%.Infrastructure.Seeders;

/// <summary>
/// %DISPLAY_DOC% 菜单登记：页面行与按钮行
/// </summary>
/// <remarks>
/// 按约定注册，由平台的汇总种子在菜单阶段最后统一写入（此时平台各模块的目录都已就位）：不需要登记种子，也没有自己的种子顺序号。
/// 页面绑定 %RESOURCE%:read 控制可见；页面按钮用按钮码 %PAGECODE%.{create|update|delete…} 门控，按钮码只由这里的按钮行下发。
/// 父菜单取表配置的「父菜单」；排序、启停、显隐归运营，在菜单管理页调整（种子只在插入时写排序）。
/// </remarks>
[ExposeServices(typeof(IMenuPageContribution))]
public sealed class %CLASS%MenuPages : IMenuPageContribution, ITransientDependency
{
    /// <summary>登记名</summary>
    public string Name => "[%MODULE%]%DISPLAY%菜单";

    /// <summary>页面</summary>
    public IReadOnlyList<PageDescriptor> Pages { get; } =
    [
        new("%PAGECODE%", "%DISPLAY%", I18nKey: null, MenuType.Menu, "%PATH%", "%ROUTE%", "%COMPONENT%",
            ParentCode: %PARENT%, %CLASS%PermissionCodes.Read, "lucide:table", 999),
    ];

    /// <summary>页面内按钮</summary>
    public IReadOnlyList<ButtonDescriptor> Buttons { get; } =
    [
%BUTTONS%
    ];
}
""";
}
