#region <<版权版本注释>>

// ----------------------------------------------------------------
// Copyright ©2021-Present ZhaiFanhua All Rights Reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// FileName:SysRoleButtonMenuSeeder
// Guid:2f24d3c3-9d4d-4f67-8c6d-6f8d0c9a7a11
// Author:zhaifanhua
// Email:me@zhaifanhua.com
// CreateTime:2026/04/10 00:00:00
// ----------------------------------------------------------------

#endregion <<版权版本注释>>

using Microsoft.Extensions.Logging;
using XiHan.BasicApp.Saas.Domain.Entities;
using XiHan.BasicApp.Saas.Domain.Enums;
using XiHan.Framework.Data.SqlSugar;
using XiHan.Framework.Data.SqlSugar.Seeders;

namespace XiHan.BasicApp.Saas.Seeders;

/// <summary>
/// 角色按钮菜单增量种子数据
/// 将「角色-权限」中的按钮类权限同步为「角色-按钮菜单」映射，并自动补齐按钮菜单节点。
/// </summary>
public class SysRoleButtonMenuSeeder : DataSeederBase
{
    private const string AutoGeneratedButtonRemark = "权限按钮自动生成";
    private static readonly HashSet<string> SupportedButtonOperations = new(StringComparer.OrdinalIgnoreCase)
    {
        "create",
        "update",
        "delete"
    };

    /// <summary>
    /// 构造函数
    /// </summary>
    public SysRoleButtonMenuSeeder(ISqlSugarDbContext dbContext, ILogger<SysRoleButtonMenuSeeder> logger, IServiceProvider serviceProvider)
        : base(dbContext, logger, serviceProvider)
    {
    }

    /// <summary>
    /// 种子数据优先级
    /// </summary>
    public override int Order => 22;

    /// <summary>
    /// 种子数据名称
    /// </summary>
    public override string Name => "[Saas]角色按钮菜单增量种子数据";

    /// <summary>
    /// 种子数据实现
    /// </summary>
    protected override async Task SeedInternalAsync()
    {
        var db = DbContext.GetClient();
        var removedButtonMenuCount = 0;
        var removedRoleMenuCount = 0;
        var pageMenus = await db.Queryable<SysMenu>()
            .Where(menu =>
                menu.Status == YesOrNo.Yes
                && menu.MenuType == MenuType.Menu
                && menu.MenuCode != null
                && menu.MenuCode != "")
            .ToListAsync();
        if (pageMenus.Count == 0)
        {
            Logger.LogWarning("未找到页面菜单节点，跳过角色按钮菜单增量种子");
            return;
        }

        var pageMenuIdSet = pageMenus
            .Select(menu => menu.BasicId)
            .ToHashSet();
        var parentMenuMap = pageMenus
            .GroupBy(menu => BuildScopedCodeKey(menu.TenantId, menu.MenuCode))
            .ToDictionary(
                group => group.Key,
                group => group
                    .OrderBy(menu => menu.BasicId)
                    .First(),
                StringComparer.OrdinalIgnoreCase);

        // 清理历史自动生成、但不属于当前前端按钮模型（仅页面菜单 + create/update/delete）的按钮节点。
        var autoGeneratedButtonMenus = await db.Queryable<SysMenu>()
            .Where(menu =>
                menu.MenuType == MenuType.Button
                && menu.Remark == AutoGeneratedButtonRemark
                && menu.MenuCode != null
                && menu.MenuCode != "")
            .ToListAsync();
        if (autoGeneratedButtonMenus.Count > 0)
        {
            var staleButtonMenuIds = autoGeneratedButtonMenus
                .Where(menu =>
                    !TryParsePermissionCode(menu.MenuCode!, out _, out var operationCode)
                    || !ShouldSyncAsButton(operationCode)
                    || !menu.ParentId.HasValue
                    || !pageMenuIdSet.Contains(menu.ParentId.Value))
                .Select(menu => menu.BasicId)
                .Distinct()
                .ToArray();
            if (staleButtonMenuIds.Length > 0)
            {
                removedRoleMenuCount = await db.Deleteable<SysRoleMenu>()
                    .Where(mapping => staleButtonMenuIds.Contains(mapping.MenuId))
                    .ExecuteCommandAsync();
                removedButtonMenuCount = await db.Deleteable<SysMenu>()
                    .Where(menu => staleButtonMenuIds.Contains(menu.BasicId))
                    .ExecuteCommandAsync();
            }
        }

        var permissions = await db.Queryable<SysPermission>()
            .Where(permission => permission.Status == YesOrNo.Yes && permission.PermissionCode != null && permission.PermissionCode != "")
            .ToListAsync();
        if (permissions.Count == 0)
        {
            Logger.LogWarning("权限数据为空，跳过角色按钮菜单增量种子");
            return;
        }

        var operations = await db.Queryable<SysOperation>().ToListAsync();
        var operationNameMap = operations
            .Where(operation => !string.IsNullOrWhiteSpace(operation.OperationName))
            .ToDictionary(operation => operation.BasicId, operation => operation.OperationName.Trim());

        var existingButtonMenus = await db.Queryable<SysMenu>()
            .Where(menu => menu.MenuType == MenuType.Button && menu.MenuCode != null && menu.MenuCode != "" && menu.ParentId != null)
            .ToListAsync();
        var existingButtonMenuKeys = existingButtonMenus
            .Where(menu => menu.ParentId.HasValue && pageMenuIdSet.Contains(menu.ParentId.Value))
            .Select(menu => BuildButtonMenuKey(menu.TenantId, menu.ParentId!.Value, menu.MenuCode!))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        var buttonMenuInserts = new List<SysMenu>();

        foreach (var permission in permissions)
        {
            if (!TryParsePermissionCode(permission.PermissionCode, out var resourceCode, out var operationCode))
            {
                continue;
            }

            if (!ShouldSyncAsButton(operationCode))
            {
                continue;
            }

            if (!parentMenuMap.TryGetValue(BuildScopedCodeKey(permission.TenantId, resourceCode), out var parentMenu))
            {
                continue;
            }

            var menuCode = NormalizePermissionCode(permission.PermissionCode);
            var buttonMenuKey = BuildButtonMenuKey(parentMenu.TenantId, parentMenu.BasicId, menuCode);
            if (existingButtonMenuKeys.Contains(buttonMenuKey))
            {
                continue;
            }

            var operationName = operationNameMap.TryGetValue(permission.OperationId, out var name)
                ? name
                : operationCode;
            if (string.IsNullOrWhiteSpace(operationName))
            {
                operationName = "按钮";
            }

            buttonMenuInserts.Add(new SysMenu
            {
                TenantId = parentMenu.TenantId,
                ResourceId = permission.ResourceId,
                ParentId = parentMenu.BasicId,
                MenuName = operationName,
                MenuCode = menuCode,
                MenuType = MenuType.Button,
                IsExternal = false,
                IsCache = false,
                IsVisible = false,
                IsAffix = false,
                BadgeDot = false,
                Status = YesOrNo.Yes,
                Sort = permission.Sort > 0 ? permission.Sort : 9000,
                Remark = AutoGeneratedButtonRemark
            });
            existingButtonMenuKeys.Add(buttonMenuKey);
        }

        if (buttonMenuInserts.Count > 0)
        {
            await BulkInsertAsync(buttonMenuInserts);
        }

        var allButtonMenus = await db.Queryable<SysMenu>()
            .Where(menu => menu.MenuType == MenuType.Button && menu.MenuCode != null && menu.MenuCode != "" && menu.ParentId != null)
            .ToListAsync();
        var buttonMenuMap = allButtonMenus
            .Where(menu => menu.ParentId.HasValue && pageMenuIdSet.Contains(menu.ParentId.Value))
            .GroupBy(menu => BuildButtonMenuKey(menu.TenantId, menu.ParentId!.Value, menu.MenuCode!))
            .ToDictionary(
                group => group.Key,
                group => group
                    .OrderBy(menu => menu.BasicId)
                    .First(),
                StringComparer.OrdinalIgnoreCase);

        var rolePermissions = await db.Queryable<SysRolePermission>()
            .Where(mapping => mapping.Status == YesOrNo.Yes)
            .ToListAsync();
        if (rolePermissions.Count == 0)
        {
            Logger.LogInformation(
                "角色按钮菜单种子完成：清理按钮菜单 {RemovedButtonMenuCount} 条，清理角色按钮菜单 {RemovedRoleMenuCount} 条，新增按钮菜单 {ButtonMenuCount} 条，新增角色按钮菜单 {RoleMenuCount} 条",
                removedButtonMenuCount,
                removedRoleMenuCount,
                buttonMenuInserts.Count,
                0);
            return;
        }

        var permissionMap = permissions.ToDictionary(permission => permission.BasicId);
        var existingRoleMenuPairs = await db.Queryable<SysRoleMenu>()
            .Where(mapping => mapping.Status == YesOrNo.Yes)
            .Select(mapping => new { mapping.RoleId, mapping.MenuId })
            .ToListAsync();
        var existingRoleMenuSet = existingRoleMenuPairs
            .Select(pair => $"{pair.RoleId}_{pair.MenuId}")
            .ToHashSet(StringComparer.Ordinal);

        var roleMenuInserts = new List<SysRoleMenu>();
        foreach (var mapping in rolePermissions)
        {
            if (!permissionMap.TryGetValue(mapping.PermissionId, out var permission))
            {
                continue;
            }

            if (!TryParsePermissionCode(permission.PermissionCode, out var resourceCode, out var operationCode))
            {
                continue;
            }

            if (!ShouldSyncAsButton(operationCode))
            {
                continue;
            }

            if (!parentMenuMap.TryGetValue(BuildScopedCodeKey(permission.TenantId, resourceCode), out var parentMenu))
            {
                continue;
            }

            var menuCode = NormalizePermissionCode(permission.PermissionCode);
            var buttonMenuKey = BuildButtonMenuKey(parentMenu.TenantId, parentMenu.BasicId, menuCode);
            if (!buttonMenuMap.TryGetValue(buttonMenuKey, out var buttonMenu))
            {
                continue;
            }

            var pairKey = $"{mapping.RoleId}_{buttonMenu.BasicId}";
            if (!existingRoleMenuSet.Add(pairKey))
            {
                continue;
            }

            roleMenuInserts.Add(new SysRoleMenu
            {
                TenantId = mapping.TenantId ?? buttonMenu.TenantId,
                RoleId = mapping.RoleId,
                MenuId = buttonMenu.BasicId,
                Status = YesOrNo.Yes
            });
        }

        if (roleMenuInserts.Count > 0)
        {
            await BulkInsertAsync(roleMenuInserts);
        }

        Logger.LogInformation(
            "角色按钮菜单种子完成：清理按钮菜单 {RemovedButtonMenuCount} 条，清理角色按钮菜单 {RemovedRoleMenuCount} 条，新增按钮菜单 {ButtonMenuCount} 条，新增角色按钮菜单 {RoleMenuCount} 条",
            removedButtonMenuCount,
            removedRoleMenuCount,
            buttonMenuInserts.Count,
            roleMenuInserts.Count);
    }

    private static string NormalizePermissionCode(string permissionCode)
    {
        return permissionCode.Trim().ToLowerInvariant();
    }

    private static bool TryParsePermissionCode(string permissionCode, out string resourceCode, out string operationCode)
    {
        resourceCode = string.Empty;
        operationCode = string.Empty;
        if (string.IsNullOrWhiteSpace(permissionCode))
        {
            return false;
        }

        var normalizedCode = NormalizePermissionCode(permissionCode);
        var separatorIndex = normalizedCode.IndexOf(':');
        if (separatorIndex <= 0 || separatorIndex >= normalizedCode.Length - 1)
        {
            return false;
        }

        resourceCode = normalizedCode[..separatorIndex].Trim();
        operationCode = normalizedCode[(separatorIndex + 1)..].Trim();
        return !string.IsNullOrWhiteSpace(resourceCode) && !string.IsNullOrWhiteSpace(operationCode);
    }

    private static bool ShouldSyncAsButton(string operationCode)
    {
        return SupportedButtonOperations.Contains(operationCode);
    }

    private static string BuildScopedCodeKey(long? tenantId, string code)
    {
        return $"{tenantId?.ToString() ?? "0"}:{code.Trim().ToLowerInvariant()}";
    }

    private static string BuildButtonMenuKey(long? tenantId, long parentId, string menuCode)
    {
        return $"{tenantId?.ToString() ?? "0"}:{parentId}:{menuCode.Trim().ToLowerInvariant()}";
    }
}
