<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\..\props\netcore.props" />
    <Import Project="..\..\..\props\common.props" />
    <Import Project="..\..\..\props\version.props" />
    <Import Project="..\..\..\props\nuget.props" />

    <PropertyGroup>
        <Title>XiHan.BasicApp.Printing</Title>
        <AssemblyName>XiHan.BasicApp.Printing</AssemblyName>
        <PackageId>XiHan.BasicApp.Printing</PackageId>
        <Description>曦寒基础应用打印库</Description>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\XiHan.BasicApp.Saas\XiHan.BasicApp.Saas.csproj" />
    </ItemGroup>

</Project>
