export * from './base'
// 资源工厂：docs/frontend/development.md 与 docs/frontend/request.md 都把 defineResource 列为标准 CRUD 的写法，
// 此前桶文件漏挂，照文档写 `import { defineResource } from '@/api'` 只会拿到 undefined（export * 不报编译错）。
export * from './factory'
export * from './helpers'
export * from './modules/audit'
export * from './modules/authorization'
export * from './modules/cache'
export * from './modules/configuration'
export * from './modules/constraint-rule'
export * from './modules/export'
export * from './modules/files'
export * from './modules/identity'
export * from './modules/log'
export * from './modules/messaging'
export * from './modules/metadata'
export * from './modules/navigation'
export * from './modules/oauth'
export * from './modules/organization'
export * from './modules/platform'
export * from './modules/server'
export * from './modules/system'
export * from './modules/tenant'
export * from './modules/workbench'
export * from './modules/workflow'
export * from './request'
export * from './types'
