-- 业务编号模块 MySQL 8 正向脚本。
-- 运行时仍以 SqlSugar CodeFirst 为主；本脚本用于受控数据库发布和人工审阅。
-- MySQL DDL 会隐式提交；请在受控维护窗口执行，并在执行前完成数据库备份。

CREATE TABLE `Sys_Numbering_Rule` (
    `Basic_Id` BIGINT NOT NULL,
    `Row_Version` BIGINT NOT NULL DEFAULT 0,
    `Tenant_Id` BIGINT NOT NULL DEFAULT 0,
    `Rule_Code` VARCHAR(100) NOT NULL,
    `Rule_Name` VARCHAR(100) NOT NULL,
    `Prefix` VARCHAR(50) NULL,
    `Separator` VARCHAR(10) NOT NULL DEFAULT '-',
    `Date_Format` INT NOT NULL DEFAULT 3,
    `Serial_Length` INT NOT NULL DEFAULT 4,
    `Reset_Cycle` INT NOT NULL DEFAULT 1,
    `Time_Zone_Id` VARCHAR(100) NOT NULL DEFAULT 'UTC',
    `Current_Value` BIGINT NOT NULL DEFAULT 0,
    `Current_Period` VARCHAR(32) NULL,
    `Has_Allocated` TINYINT(1) NOT NULL DEFAULT 0,
    `Allow_Tenant_Use` TINYINT(1) NOT NULL DEFAULT 0,
    `Status` INT NOT NULL DEFAULT 1,
    `Sort` INT NOT NULL DEFAULT 0,
    `Remark` VARCHAR(500) NULL,
    `Created_Time` DATETIME(6) NOT NULL,
    `Created_Id` BIGINT NULL,
    `Created_By` VARCHAR(100) NULL,
    `Modified_Time` DATETIME(6) NULL,
    `Modified_Id` BIGINT NULL,
    `Modified_By` VARCHAR(100) NULL,
    `Is_Deleted` TINYINT(1) NOT NULL DEFAULT 0,
    `Deleted_Time` DATETIME(6) NULL,
    `Deleted_Id` BIGINT NULL,
    `Deleted_By` VARCHAR(100) NULL,
    PRIMARY KEY (`Basic_Id`),
    CONSTRAINT `CK_Sys_Numbering_Rule_Serial_Length` CHECK (`Serial_Length` BETWEEN 1 AND 18),
    CONSTRAINT `CK_Sys_Numbering_Rule_Current_Value` CHECK (`Current_Value` >= 0),
    UNIQUE KEY `UX_Sys_Numbering_Rule_TeId_RuCo` (`Tenant_Id`, `Rule_Code`, `Is_Deleted`),
    KEY `IX_Sys_Numbering_Rule_TeId_CrTi` (`Tenant_Id`, `Created_Time` DESC),
    KEY `IX_Sys_Numbering_Rule_CrId` (`Created_Id`),
    KEY `IX_Sys_Numbering_Rule_TeId_IsDe` (`Tenant_Id`, `Is_Deleted`),
    KEY `IX_Sys_Numbering_Rule_TeId_St_So` (`Tenant_Id`, `Status`, `Sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `Sys_Numbering_Allocation` (
    `Basic_Id` BIGINT NOT NULL,
    `Row_Version` BIGINT NOT NULL DEFAULT 0,
    `Tenant_Id` BIGINT NOT NULL DEFAULT 0,
    `Rule_Id` BIGINT NOT NULL,
    `Rule_Code` VARCHAR(100) NOT NULL,
    `Request_Tenant_Id` BIGINT NOT NULL DEFAULT 0,
    `Idempotency_Key` VARCHAR(100) NOT NULL,
    `Request_Fingerprint` CHAR(64) NOT NULL,
    `Allocation_Count` INT NOT NULL,
    `Start_Value` BIGINT NOT NULL,
    `End_Value` BIGINT NOT NULL,
    `Period_Key` VARCHAR(32) NOT NULL,
    `Prefix_Snapshot` VARCHAR(50) NULL,
    `Separator_Snapshot` VARCHAR(10) NOT NULL,
    `Date_Text_Snapshot` VARCHAR(16) NULL,
    `Serial_Length_Snapshot` INT NOT NULL,
    `Generated_At_Utc` DATETIME(6) NOT NULL,
    `Business_Type` VARCHAR(100) NULL,
    `Business_Id` VARCHAR(100) NULL,
    `Created_Time` DATETIME(6) NOT NULL,
    `Created_Id` BIGINT NULL,
    `Created_By` VARCHAR(100) NULL,
    PRIMARY KEY (`Basic_Id`),
    CONSTRAINT `CK_Sys_Numbering_Allocation_Count` CHECK (`Allocation_Count` BETWEEN 1 AND 1000),
    CONSTRAINT `CK_Sys_Numbering_Allocation_Range` CHECK (`Start_Value` >= 1 AND `End_Value` >= `Start_Value`),
    UNIQUE KEY `UX_Sys_Numbering_Allocation_Ru_ReTe_IdKe` (`Tenant_Id`, `Rule_Id`, `Request_Tenant_Id`, `Idempotency_Key`),
    KEY `IX_Sys_Numbering_Allocation_TeId_CrTi` (`Tenant_Id`, `Created_Time` DESC),
    KEY `IX_Sys_Numbering_Allocation_CrId` (`Created_Id`),
    KEY `IX_Sys_Numbering_Allocation_Ru_GeTi` (`Rule_Id`, `Generated_At_Utc` DESC),
    KEY `IX_Sys_Numbering_Allocation_ReTe_GeTi` (`Request_Tenant_Id`, `Generated_At_Utc` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
