<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\..\props\netcore.props" />
    <Import Project="..\..\..\props\common.props" />
    <Import Project="..\..\..\props\version.props" />
    <Import Project="..\..\..\props\nuget.props" />

    <PropertyGroup>
        <Title>XiHan.BasicApp.Sample</Title>
        <AssemblyName>XiHan.BasicApp.Sample</AssemblyName>
        <PackageId>XiHan.BasicApp.Sample</PackageId>
        <Description>曦寒基础应用示例业务库</Description>
        <OutputType>Library</OutputType>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\modules\XiHan.BasicApp.Saas\XiHan.BasicApp.Saas.csproj" />
    </ItemGroup>

</Project>
